# Generated by Django 2.0.2 on 2020-11-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_job_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='summary',
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='technologies',
            field=models.TextField(default=''),
        ),
    ]
