# Generated by Django 2.0.2 on 2020-11-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20201122_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_date',
            new_name='end_job_date',
        ),
        migrations.AddField(
            model_name='job',
            name='str_job_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
