# Generated by Django 2.0.2 on 2020-11-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20201122_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='position',
            field=models.CharField(default='', max_length=200),
        ),
    ]
