# Generated by Django 2.0.2 on 2020-11-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='technologies',
            field=models.TextField(blank=True, default=''),
        ),
    ]
