# Generated by Django 2.0.2 on 2020-11-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20201122_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True, default=''),
        ),
    ]
